### ISSUE TITLE
add outline none as an accessibility issue

### ISSUE THREAD

**Issue by EmanoelLopes** [Stefanye/CSSHell#13]
Perhaps in the same way as the [link without the text-decoration](https://csshell.dev/posts/link-and-the-forgotten-accessibility/), a button or input without the outline can cause an accessibility problem.

**Comment by Stefanye** [comment]
This is not an issue, but rather a suggestion for posts. Please use the Discussions tab for ideas :) 

(anyway, good one, noted!)
