### ISSUE TITLE
Merge commands for serve and watch:sass

### ISSUE THREAD

**Issue by Stefanye** [Stefanye/CSSHell#15]

**Comment by xleepy** [comment]
Hi, what about [concurrently](https://www.npmjs.com/package/concurrently) npm package. Should work on unix-like and windows systems
Can be used like that
`
 "start:dev": "concurrently \"npm run serve\"  \"npm run watch:sass\""
`
Also i think would be great to add build-sass command.
And sorry did something wrong this is my first comment on issue ever so

**Comment by Stefanye** [comment]
Thanks for the suggestion @xleepy! Will check it out :)
