### ISSUE TITLE
relative units clarification

### ISSUE THREAD

**Issue by marcelmoreau** [Stefanye/CSSHell#20]
I am not sure if you think this warrants a PR.

https://csshell.dev/posts/lets-talk-about-units/

The _Good example_ sizes a paragraph's `font-size` at `1rem`. It might be explained that `rem` font-size is relative to the font-size of the root element(`:root` or `<html>`), not `<body>`.  If a user took the existing example to their project, but modified their `<body>`'s font-size, they might wonder "why does my paragraph's 1rem font-size not match my 22px?" Here is an example of that: https://codepen.io/marcelmoreau/pen/NWpXPEq

This might be made more clear by changing the example's `body` selector to `html` and removing the `font-size: 16px` from it.

Also, it might also be more clear to change the formula from `size / base-font-size` to `desired-size / root-font-size`

I am happy to make a PR for this, but wanted to run it by you first before I do all that.

**Comment by Stefanye** [comment]
Hi!
You got a point there! I will fix it soon! Thanks :)
