### ISSUE TITLE
Support email newsletter 🙂

### ISSUE THREAD

**Issue by babramczyk** [Stefanye/CSSHell#21]
Love the website and posts 😀

I’d love to subscribe to them, but only subscribe to things typically through email.

Would love to be able to get emails for new posts 🙂

**Comment by karesztrk** [comment]
Likewise

**Comment by Stefanye** [comment]
Not planning it for now. I don't have regular posts (not posts at all in the past 2 weeks ~.~), and still got several to-dos on the site. We will see what the future hold :) 

You can follow on Twitter and got an RSS feed too!
